[package]
name = "portal"
version = "0.1.0"
authors = ["Dan McGrady <daniel.p.mcgrady@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.10.0"
tempdir = "0.3.7"
